=== api-evangelist/amazon-app-runner/json-schema/amazon-app-runner-service-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Service",
  "description": "<p>Describes an App Runner service. It can describe a service in any state, including deleted services.</p> <p>This type contains the full information about a service, including configuration details. It's returned by the <a href=\"https://docs.aws.amazon.com/apprunner/latest/api/API_CreateService.html\">CreateService</a>, <a href=\"https://docs.aws.amazon.com/apprunner/latest/api/API_DescribeService.html\">DescribeService</a>, and <a href=\"https://docs.aws.amazon.com/apprunner/latest/api/API_DeleteService.html\">DeleteService</a> actions. A subset of this information is returned by the <a href=\"https://docs.aws.amazon.com/apprunner/latest/api/API_ListServices.html\">ListServices</a> action using the <a href=\"https://docs.aws.amazon.com/apprunner/latest/api/API_ServiceSummary.html\">ServiceSummary</a> type.</p>",
  "type": "object",
  "properties": {
    "ServiceName": {},
    "ServiceId": {},
    "ServiceArn": {},
    "ServiceUrl": {},
    "CreatedAt": {},
    "UpdatedAt": {},
    "DeletedAt": {},
    "Status": {},
    "SourceConfiguration": {},
    "InstanceConfiguration": {},
    "EncryptionConfiguration": {},
    "HealthCheckConfiguration": {},
    "AutoScalingConfigurationSummary": {},
    "NetworkConfiguration": {},
    "ObservabilityConfiguration": {}
  },
  "required": [
    "ServiceName",
    "ServiceId",
    "ServiceArn",
    "CreatedAt",
    "UpdatedAt",
    "Status",
    "SourceConfiguration",
    "InstanceConfiguration",
    "AutoScalingConfigurationSummary",
    "NetworkConfiguration"
  ]
}

=== api-evangelist/amazon-app-runner/examples/amazon-app-runner-service-example.json
{
  "ServiceName": "example-ServiceName",
  "ServiceId": "example-ServiceId",
  "ServiceArn": "example-ServiceArn",
  "ServiceUrl": "example-ServiceUrl",
  "CreatedAt": "example-CreatedAt",
  "UpdatedAt": "example-UpdatedAt",
  "DeletedAt": "example-DeletedAt",
  "Status": "example-Status",
  "SourceConfiguration": "example-SourceConfiguration",
  "InstanceConfiguration": "example-InstanceConfiguration",
  "EncryptionConfiguration": "example-EncryptionConfiguration",
  "HealthCheckConfiguration": "example-HealthCheckConfiguration",
  "AutoScalingConfigurationSummary": "example-AutoScalingConfigurationSummary",
  "NetworkConfiguration": "example-NetworkConfiguration",
  "ObservabilityConfiguration": "example-ObservabilityConfiguration"
}
